### PR TITLE
close #110, remove outdated config.env

### LINKED ISSUE #110: config.env is outdated
## Current Behavior
config/config.env contains obsolete configuration, it won't work with the current code.

## Expected Behavior
Either it should be up to date, or it can be deleted.

### PR DESCRIPTION
**Pull request by 532910**

### CODE REVIEW

**Comment by roman-khimov** [comment]
It should be updated, not deleted.

**Comment by 532910** [comment]
https://github.com/nspcc-dev/neo-exporter/issues/110

> Either it should be up to date, or it can be deleted.

**Comment by roman-khimov** [comment]
OK, after discussion with @smallhive we agreed to drop it for now, but to deal with #110 we also need to update Docker configs.

**Review by smallhive — APPROVED** [review]

**Comment by roman-khimov** [comment]
Please update README then, it still mentions Docker.

**Comment by roman-khimov** [comment]
Still mentions Docker. We also have targets in Makefile.

**Review by roman-khimov — APPROVED** [review]

**Pull request merged**
